# Generated by Django 4.2.4 on 2023-11-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresa tu nombre', max_length=100)),
                ('apellido', models.CharField(help_text='Ingresa tu apellido', max_length=100)),
                ('fecha_nac', models.DateField(help_text='Ingresa tu fecha de nacimiento', max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, help_text='Ingresa tu email', max_length=254, null=True)),
            ],
        ),
    ]
