# Generated by Django 4.2.4 on 2023-11-19 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='SKU',
            field=models.CharField(default='', help_text='Ingresa el SKU del producto', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='calificacion',
            field=models.IntegerField(help_text='Calificación del producto de 1 a 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='', help_text='Descripción del producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False, help_text='¿El producto está en oferta?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioactual',
            field=models.IntegerField(help_text='Precio actual del producto', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioanterior',
            field=models.IntegerField(help_text='Precio anterior del producto en oferta', null=True),
        ),
    ]
