# Generated by Django 4.2.4 on 2023-11-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_sku_producto_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(help_text='Imagen en lista del producto', null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(help_text='Imagen detalle del producto', null=True, upload_to='productos'),
        ),
    ]
