# Generated by Django 4.2.4 on 2023-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contacto_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='profesion',
            field=models.ManyToManyField(help_text='Ingresa la profesion', to='core.profesion'),
        ),
    ]
