# Generated by Django 4.2.4 on 2023-11-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_profesion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesion',
            options={'verbose_name': 'Profesion', 'verbose_name_plural': 'Profesiones'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(default='Desconocido', help_text='Ingresa tu apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default='Desconocido', help_text='Ingresa tu nombre', max_length=100),
        ),
    ]
