# Generated by Django 4.2.4 on 2023-12-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contacto_apellido_alter_contacto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now=True)),
                ('producto', models.CharField(help_text='Ingresa nombre Producto', max_length=200)),
                ('cliente', models.CharField(help_text='Ingresa nombre Cliente', max_length=200)),
                ('cantidad', models.IntegerField(help_text='Cantidad de Producto')),
                ('precio', models.IntegerField(help_text='Precio de Producto')),
                ('total', models.IntegerField(help_text='Total')),
            ],
        ),
    ]
