from django.shortcuts import render
from datetime import datetime

# Create your views here.

def index(request):
    return render(request, "core/index.html")

def producto(request, producto_id):
    # Convierte producto_id a un entero
    producto_id = int(producto_id)

    # Definir un diccionario con los detalles de los productos (simulado)
    productos = {
                1: {"nombre":"Zapatillas",
                "id": 1,
                "SKU": "ZAP-498",
                "descripcion": "Unas lindas zapatillas que se ven bien tanto de viaje, uso diario o incluso cuando salgas con tus amigos. Todo es material de cuero",
                "calificacion": 5,
                "oferta": "En oferta",
                "precioanterior": "$40.000", 
                "precioactual":"$35.000", 
                "imagen1": "zapatillas.png",
                "imagen2": "zapatillas2.png" },
                2: {"nombre":"Botas", 
                "id": 2,
                "SKU": "BOT-723",
                "descripcion": "Estas botas te acompañarán en todas, son perfectas para causar impresión en una salida nocturna o cuando vas de viaje. Todo es material de cuero",
                "calificacion": 3,
                "oferta": "En oferta",
                "precioanterior": "$70.000", 
                "precioactual":"$60.000", 
                "imagen1": "botas.png",
                "imagen2": "botas2.png" },
                3: {"nombre":"Sandalias",
                "id": 3, 
                "SKU": "SAND-842",
                "descripcion": "Estas sandalias no solo son onderas, sino que te permitirán tener tus pies frescos y cómodos en cualquier viaje que hagas. Todo es material de cuero",
                "calificacion": 2.5,
                "oferta": "",
                "precioanterior": " ", 
                "precioactual":"$25.000", 
                "imagen1": "sandalias.png",
                "imagen2": "sandalias2.png" },
                4: {"nombre":"Pantuflas",
                "id": 4,
                "SKU": "PANT-934",
                "descripcion": "Si llegas del trabajo cansado y con ganas de colocarte algo más cómodo, estas pantuflas te vendrán de maravilla, son cómodas, bonitas y tus pies se sentirán de maravilla",
                "calificacion": 4,
                "oferta": "",
                "precioanterior": " ",  
                "precioactual":"$20.000", 
                "imagen1": "pantuflas.png",
                "imagen2": "pantuflas2.png" },
                5: {"nombre":"Mocasines",
                "id": 5,
                "SKU": "MOC-536",
                "descripcion": "¿Cansado de zapatos duros?, estos mocasines son perfectos para cualquier ocasión, ya sea de trabajo o de vida cotidiana. Todo es material de cuero.",
                "calificacion": 5,
                "oferta": "En oferta",
                "precioanterior": "$40.000", 
                "precioactual":"$30.000", 
                "imagen1": "mocasines.png",
                "imagen2": "mocasines2.png" },
                6: {"nombre":"Crocs", 
                "id": 6,
                "SKU": "CROC-499",
                "descripcion": "Estos zapatos son famosos por su excelente comodidad, además de ser útiles para tu quehacer cotidiano, donde tus pies se sentirán frescos y cómodos",
                "calificacion": 3.5,
                "oferta": "",
                "precioanterior": " ", 
                "precioactual":"$25.000", 
                "imagen1": "crocs.png",
                "imagen2": "crocs2.png" },
                7: {"nombre":"Bamers",
                "id": 7,
                "SKU": "BAM-334",
                "descripcion": "Esta marca ha revolucionado la forma en que mantendrás tus pies calientes ante cualquier panorama, ya sea en tu trabajo, vida cotidiana o viaje. Te aseguramos comodidad.",
                "calificacion": 5,
                "oferta": "En oferta",
                "precioanterior": "$40.000",  
                "precioactual":"$35.000", 
                "imagen1": "bamers.png",
                "imagen2": "bamers2.png" },
                8: {"nombre":"Condoritas",
                "id": 8,
                "SKU": "COND-009",
                "descripcion": "Ya sea para tu baño o vacaciones, e incluso paseos por la ciudad, estas condoritas ofrecen frescura y al mismo tiempo de calidad, ya que son fabricadas con caucho de primera calidad",
                "calificacion": 3,
                "oferta": "",
                "precioanterior": " ", 
                "precioactual":"$15.000", 
                "imagen1": "condoritas.png",
                "imagen2": "condoritas2.png" },
    }

    # Obtén los detalles del producto según el producto_id
    producto = productos.get(producto_id)
    return render(request, 'core/producto.html', {'producto': producto})

def productos(request):
    ahora = datetime.now()
    #Datos parta renderizar  
    #Se genera diccionario con información de los zapatos.
    productos =  {
                "zapato1": {"nombre":"Zapatillas",
                "id": 1,
                "SKU": "ZAP-498",
                "descripcion": "Unas lindas zapatillas que se ven bien tanto de viaje, uso diario o incluso cuando salgas con tus amigos. Todo es material de cuero",
                "calificacion": 5,
                "oferta": "En oferta",
                "precioanterior": "$40.000", 
                "precioactual":"$35.000", 
                "imagen1": "zapatillas.png",
                "imagen2": "zapatillas2.png" },
                "zapato2": {"nombre":"Botas", 
                "id": 2,
                "SKU": "BOT-723",
                "descripcion": "Estas botas te acompañarán en todas, son perfectas para causar impresión en una salida nocturna o cuando vas de viaje. Todo es material de cuero",
                "calificacion": 3,
                "oferta": "En oferta",
                "precioanterior": "$70.000", 
                "precioactual":"$60.000", 
                "imagen1": "botas.png",
                "imagen2": "botas2.png" },
                "zapato3": {"nombre":"Sandalias",
                "id": 3, 
                "SKU": "SAND-842",
                "descripcion": "Estas sandalias no solo son onderas, sino que te permitirán tener tus pies frescos y cómodos en cualquier viaje que hagas. Todo es material de cuero",
                "calificacion": 2.5,
                "oferta": "",
                "precioanterior": " ", 
                "precioactual":"$25.000", 
                "imagen1": "sandalias.png",
                "imagen2": "sandalias2.png" },
                "zapato4": {"nombre":"Pantuflas",
                "id": 4,
                "SKU": "PANT-934",
                "descripcion": "Si llegas del trabajo cansado y con ganas de colocarte algo más cómodo, estas pantuflas te vendrán de maravilla, son cómodas, bonitas y tus pies se sentirán de maravilla",
                "calificacion": 4,
                "oferta": "",
                "precioanterior": " ",  
                "precioactual":"$20.000", 
                "imagen1": "pantuflas.png",
                "imagen2": "pantuflas2.png" },
                "zapato5": {"nombre":"Mocasines",
                "id": 5,
                "SKU": "MOC-536",
                "descripcion": "¿Cansado de zapatos duros?, estos mocasines son perfectos para cualquier ocasión, ya sea de trabajo o de vida cotidiana. Todo es material de cuero.",
                "calificacion": 5,
                "oferta": "En oferta",
                "precioanterior": "$40.000", 
                "precioactual":"$30.000", 
                "imagen1": "mocasines.png",
                "imagen2": "mocasines2.png" },
                "zapato6": {"nombre":"Crocs", 
                "id": 6,
                "SKU": "CROC-499",
                "descripcion": "Estos zapatos son famosos por su excelente comodidad, además de ser útiles para tu quehacer cotidiano, donde tus pies se sentirán frescos y cómodos",
                "calificacion": 3.5,
                "oferta": "",
                "precioanterior": " ", 
                "precioactual":"$25.000", 
                "imagen1": "crocs.png",
                "imagen2": "crocs2.png" },
                "zapato7": {"nombre":"Bamers",
                "id": 7,
                "SKU": "BAM-334",
                "descripcion": "Esta marca ha revolucionado la forma en que mantendrás tus pies calientes ante cualquier panorama, ya sea en tu trabajo, vida cotidiana o viaje. Te aseguramos comodidad.",
                "calificacion": 5,
                "oferta": "En oferta",
                "precioanterior": "$40.000",  
                "precioactual":"$35.000", 
                "imagen1": "bamers.png",
                "imagen2": "bamers2.png" },
                "zapato8": {"nombre":"Condoritas",
                "id": 8,
                "SKU": "COND-009",
                "descripcion": "Ya sea para tu baño o vacaciones, e incluso paseos por la ciudad, estas condoritas ofrecen frescura y al mismo tiempo de calidad, ya que son fabricadas con caucho de primera calidad",
                "calificacion": 3,
                "oferta": "",
                "precioanterior": " ", 
                "precioactual":"$15.000", 
                "imagen1": "condoritas.png",
                "imagen2": "condoritas2.png" },
                }
    
    datos = {"fecha": ahora, "productos": productos}
    return render(request, "core/productos.html", datos)

def formulario(request):
    return render(request, "core/formulario.html")